version: 2
updates:
  # Frontend package updates
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  # Backend package updates  
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
        update-types:
          - "major"
          - "minor"
          - "patch"