# Prometheus configuration file for ERD Visualization Tool
# Version: 2.45

# Global configuration settings
global:
  scrape_interval: 15s      # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules
  scrape_timeout: 10s      # Timeout for scrape requests
  external_labels:         # Labels added to any time series
    environment: production
    region: default

# Scrape configurations containing endpoints to scrape
scrape_configs:
  # Self-monitoring - Prometheus scrapes its own metrics
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scheme: http

  # API Server monitoring
  - job_name: api-server
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3000']
        labels:
          service: api
          component: backend
    scrape_interval: 10s
    scrape_timeout: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: process_.*
        action: keep

  # WebSocket Server monitoring
  - job_name: websocket-server
    metrics_path: /metrics
    static_configs:
      - targets: ['websocket:3001']
        labels:
          service: websocket
          component: realtime
    scrape_interval: 10s
    scrape_timeout: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: (socket_.*|process_.*)
        action: keep

  # Redis monitoring
  - job_name: redis
    static_configs:
      - targets: ['redis:9121']
        labels:
          service: redis
          component: cache
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: http
      timeout: 10s
      api_version: v2

# Rules files to load
rule_files:
  - /etc/prometheus/rules/*.yml

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention_time: 30d
    min_block_duration: 2h
    max_block_duration: 24h
    retention_size: 50GB