version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - sqlite-data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=file:/app/data/dev.db
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=development_access_secret_replace_in_production
      - JWT_REFRESH_SECRET=development_refresh_secret_replace_in_production
      - JWT_ISSUER=erd-tool
      - DATABASE_POOL_SIZE=10
      - REDIS_SESSION_TTL=86400
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - WS_PORT=3001
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=development_access_secret_replace_in_production
      - JWT_ISSUER=erd-tool
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --requirepass development_redis_password_replace_in_production
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "development_redis_password_replace_in_production", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

volumes:
  sqlite-data:
    driver: local
  redis-data:
    driver: local

networks:
  backend:
    driver: bridge
    driver_opts:
      encrypted: "true"