# Loki Configuration v2.8
# Purpose: Centralized logging system configuration for ERD Visualization Tool
# Retention: 90 days (2160h)

# Authentication settings
auth_enabled: false

# Server configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 67108864  # 64MB
  grpc_server_max_send_msg_size: 67108864  # 64MB

# Ingester configuration for log chunk management
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  max_chunk_age: 2h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 30s
  max_transfer_retries: 0

# Schema configuration for log storage
schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# Query and retention limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  max_entries_limit_per_query: 5000
  max_query_length: 721h  # 30 days
  max_query_parallelism: 32
  retention_period: 2160h  # 90 days

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 2160h  # 90 days

# Table manager configuration for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 2160h  # 90 days