apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: erd-visualization
  labels:
    app: erd-tool
    component: backend
    environment: ${ENV}
    version: 1.0.0
    managed-by: kubernetes
  annotations:
    # Prometheus monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
    # Session affinity settings for consistent routing
    service.beta.kubernetes.io/session-affinity: "ClientIP"
    service.beta.kubernetes.io/session-affinity-timeout: "10800"

spec:
  # Internal cluster access only
  type: ClusterIP
  
  # Port configuration for the backend API
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  
  # Label selector to match backend deployment pods
  selector:
    app: erd-tool
    component: backend
  
  # Session affinity configuration for sticky sessions
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800