apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: erd-visualization
  labels:
    app: erd-tool
    environment: ${ENV}
    component: configuration
    managed-by: kubernetes
data:
  # Node.js environment configuration
  NODE_ENV: "production"
  
  # Service ports
  PORT: "3000"
  WS_PORT: "3001"
  
  # Service URLs for internal communication
  API_URL: "http://backend-service:3000"
  WS_URL: "ws://websocket-service:3001"
  
  # CORS configuration
  CORS_ORIGIN: "https://${DOMAIN}"
  
  # Redis connection settings
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_TIMEOUT: "5000"
  
  # Frontend environment variables (Vite)
  VITE_API_URL: "https://${DOMAIN}/api"
  VITE_WS_URL: "wss://${DOMAIN}/ws"
  
  # Application limits and thresholds
  MAX_CONCURRENT_USERS: "25"
  MAX_TABLES_PER_DIAGRAM: "100"
  SYNC_LATENCY_THRESHOLD: "100"
  
  # Logging and monitoring
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"