apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: erd-visualization
  labels:
    app: erd-visualization
    component: backend
    managed-by: manual
  annotations:
    rotation-schedule: "90-days"
    last-rotated: "2024-01-01T00:00:00Z"  # Update with actual timestamp
    encryption: "AES-256-GCM"
type: Opaque
data:
  # SQLite database connection string with encryption parameters
  DATABASE_URL: "c3FsaXRlOi8vL2RhdGEvZXJkLmRiP2VuY3J5cHRpb249YWVzLTI1Ni1jYmM="

  # Redis credentials for session management and caching
  REDIS_PASSWORD: "UmVkaXNQYXNzd29yZDEyMyE="

  # JWT tokens for authentication (1-hour lifetime)
  JWT_SECRET: "and1dF9zZWNyZXRfa2V5X2Zvcl9hY2Nlc3NfdG9rZW5zXzEyMw=="

  # Refresh tokens for extended sessions (7-day lifetime)
  REFRESH_TOKEN_SECRET: "cmVmcmVzaF90b2tlbl9zZWNyZXRfa2V5X2Zvcl9leHRlbmRlZF9zZXNzaW9uc18xMjM="

  # AES-256-GCM encryption key for sensitive data
  ENCRYPTION_KEY: "YWVzXzI1Nl9nY21fZW5jcnlwdGlvbl9rZXlfZm9yX3Nlc3Npb25fZGF0YV8xMjM="

  # Auth.js secret for authentication service
  AUTH_SECRET: "YXV0aF9zZWNyZXRfa2V5X2Zvcl9hdXRoZW50aWNhdGlvbl9zZXJ2aWNlXzEyMw=="